/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CacheOptionsRouteImport } from './routes/cacheOptions'
import { Route as TanStackTableRouteImport } from './routes/tanStackTable'
import { Route as TanStackTableDynamicRouteImport } from './routes/tanStackTableDynamic'
import { Route as UseInfiniteQueryRouteImport } from './routes/useInfiniteQuery'
import { Route as UseIsFetchingRouteImport } from './routes/useIsFetching'
import { Route as UseMutationRouteImport } from './routes/useMutation'
import { Route as UseQueriesAsyncRouteImport } from './routes/useQueriesAsync'
import { Route as UseQueriesSyncRouteImport } from './routes/useQueriesSync'
import { Route as UseQueryRouteImport } from './routes/useQuery'
import { Route as UseQueryClientRouteImport } from './routes/useQueryClient'
import { Route as UseQueryWIthParamsRouteImport } from './routes/useQueryWIthParams'
import { Route as UseSuspenseQueryRouteImport } from './routes/useSuspenseQuery'

const CacheOptionsRoute = CacheOptionsRouteImport.update({
  id: '/cacheOptions',
  path: '/cacheOptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TanStackTableRoute = TanStackTableRouteImport.update({
  id: '/tanStackTable',
  path: '/tanStackTable',
  getParentRoute: () => rootRouteImport,
} as any)
const TanStackTableDynamicRoute = TanStackTableDynamicRouteImport.update({
  id: '/tanStackTableDynamic',
  path: '/tanStackTableDynamic',
  getParentRoute: () => rootRouteImport,
} as any)
const UseInfiniteQueryRoute = UseInfiniteQueryRouteImport.update({
  id: '/useInfiniteQuery',
  path: '/useInfiniteQuery',
  getParentRoute: () => rootRouteImport,
} as any)
const UseIsFetchingRoute = UseIsFetchingRouteImport.update({
  id: '/useIsFetching',
  path: '/useIsFetching',
  getParentRoute: () => rootRouteImport,
} as any)
const UseMutationRoute = UseMutationRouteImport.update({
  id: '/useMutation',
  path: '/useMutation',
  getParentRoute: () => rootRouteImport,
} as any)
const UseQueriesAsyncRoute = UseQueriesAsyncRouteImport.update({
  id: '/useQueriesAsync',
  path: '/useQueriesAsync',
  getParentRoute: () => rootRouteImport,
} as any)
const UseQueriesSyncRoute = UseQueriesSyncRouteImport.update({
  id: '/useQueriesSync',
  path: '/useQueriesSync',
  getParentRoute: () => rootRouteImport,
} as any)
const UseQueryRoute = UseQueryRouteImport.update({
  id: '/useQuery',
  path: '/useQuery',
  getParentRoute: () => rootRouteImport,
} as any)
const UseQueryClientRoute = UseQueryClientRouteImport.update({
  id: '/useQueryClient',
  path: '/useQueryClient',
  getParentRoute: () => rootRouteImport,
} as any)
const UseQueryWIthParamsRoute = UseQueryWIthParamsRouteImport.update({
  id: '/useQueryWIthParams',
  path: '/useQueryWIthParams',
  getParentRoute: () => rootRouteImport,
} as any)
const UseSuspenseQueryRoute = UseSuspenseQueryRouteImport.update({
  id: '/useSuspenseQuery',
  path: '/useSuspenseQuery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cacheOptions': typeof CacheOptionsRoute
  '/tanStackTable': typeof TanStackTableRoute
  '/tanStackTableDynamic': typeof TanStackTableDynamicRoute
  '/useInfiniteQuery': typeof UseInfiniteQueryRoute
  '/useIsFetching': typeof UseIsFetchingRoute
  '/useMutation': typeof UseMutationRoute
  '/useQueriesAsync': typeof UseQueriesAsyncRoute
  '/useQueriesSync': typeof UseQueriesSyncRoute
  '/useQuery': typeof UseQueryRoute
  '/useQueryClient': typeof UseQueryClientRoute
  '/useQueryWIthParams': typeof UseQueryWIthParamsRoute
  '/useSuspenseQuery': typeof UseSuspenseQueryRoute
}
export interface FileRoutesByTo {
  '/cacheOptions': typeof CacheOptionsRoute
  '/tanStackTable': typeof TanStackTableRoute
  '/tanStackTableDynamic': typeof TanStackTableDynamicRoute
  '/useInfiniteQuery': typeof UseInfiniteQueryRoute
  '/useIsFetching': typeof UseIsFetchingRoute
  '/useMutation': typeof UseMutationRoute
  '/useQueriesAsync': typeof UseQueriesAsyncRoute
  '/useQueriesSync': typeof UseQueriesSyncRoute
  '/useQuery': typeof UseQueryRoute
  '/useQueryClient': typeof UseQueryClientRoute
  '/useQueryWIthParams': typeof UseQueryWIthParamsRoute
  '/useSuspenseQuery': typeof UseSuspenseQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cacheOptions': typeof CacheOptionsRoute
  '/tanStackTable': typeof TanStackTableRoute
  '/tanStackTableDynamic': typeof TanStackTableDynamicRoute
  '/useInfiniteQuery': typeof UseInfiniteQueryRoute
  '/useIsFetching': typeof UseIsFetchingRoute
  '/useMutation': typeof UseMutationRoute
  '/useQueriesAsync': typeof UseQueriesAsyncRoute
  '/useQueriesSync': typeof UseQueriesSyncRoute
  '/useQuery': typeof UseQueryRoute
  '/useQueryClient': typeof UseQueryClientRoute
  '/useQueryWIthParams': typeof UseQueryWIthParamsRoute
  '/useSuspenseQuery': typeof UseSuspenseQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cacheOptions'
    | '/tanStackTable'
    | '/tanStackTableDynamic'
    | '/useInfiniteQuery'
    | '/useIsFetching'
    | '/useMutation'
    | '/useQueriesAsync'
    | '/useQueriesSync'
    | '/useQuery'
    | '/useQueryClient'
    | '/useQueryWIthParams'
    | '/useSuspenseQuery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cacheOptions'
    | '/tanStackTable'
    | '/tanStackTableDynamic'
    | '/useInfiniteQuery'
    | '/useIsFetching'
    | '/useMutation'
    | '/useQueriesAsync'
    | '/useQueriesSync'
    | '/useQuery'
    | '/useQueryClient'
    | '/useQueryWIthParams'
    | '/useSuspenseQuery'
  id:
    | '__root__'
    | '/cacheOptions'
    | '/tanStackTable'
    | '/tanStackTableDynamic'
    | '/useInfiniteQuery'
    | '/useIsFetching'
    | '/useMutation'
    | '/useQueriesAsync'
    | '/useQueriesSync'
    | '/useQuery'
    | '/useQueryClient'
    | '/useQueryWIthParams'
    | '/useSuspenseQuery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CacheOptionsRoute: typeof CacheOptionsRoute
  TanStackTableRoute: typeof TanStackTableRoute
  TanStackTableDynamicRoute: typeof TanStackTableDynamicRoute
  UseInfiniteQueryRoute: typeof UseInfiniteQueryRoute
  UseIsFetchingRoute: typeof UseIsFetchingRoute
  UseMutationRoute: typeof UseMutationRoute
  UseQueriesAsyncRoute: typeof UseQueriesAsyncRoute
  UseQueriesSyncRoute: typeof UseQueriesSyncRoute
  UseQueryRoute: typeof UseQueryRoute
  UseQueryClientRoute: typeof UseQueryClientRoute
  UseQueryWIthParamsRoute: typeof UseQueryWIthParamsRoute
  UseSuspenseQueryRoute: typeof UseSuspenseQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cacheOptions': {
      id: '/cacheOptions'
      path: '/cacheOptions'
      fullPath: '/cacheOptions'
      preLoaderRoute: typeof CacheOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanStackTable': {
      id: '/tanStackTable'
      path: '/tanStackTable'
      fullPath: '/tanStackTable'
      preLoaderRoute: typeof TanStackTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanStackTableDynamic': {
      id: '/tanStackTableDynamic'
      path: '/tanStackTableDynamic'
      fullPath: '/tanStackTableDynamic'
      preLoaderRoute: typeof TanStackTableDynamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useInfiniteQuery': {
      id: '/useInfiniteQuery'
      path: '/useInfiniteQuery'
      fullPath: '/useInfiniteQuery'
      preLoaderRoute: typeof UseInfiniteQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useIsFetching': {
      id: '/useIsFetching'
      path: '/useIsFetching'
      fullPath: '/useIsFetching'
      preLoaderRoute: typeof UseIsFetchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useMutation': {
      id: '/useMutation'
      path: '/useMutation'
      fullPath: '/useMutation'
      preLoaderRoute: typeof UseMutationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useQueriesAsync': {
      id: '/useQueriesAsync'
      path: '/useQueriesAsync'
      fullPath: '/useQueriesAsync'
      preLoaderRoute: typeof UseQueriesAsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useQueriesSync': {
      id: '/useQueriesSync'
      path: '/useQueriesSync'
      fullPath: '/useQueriesSync'
      preLoaderRoute: typeof UseQueriesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useQuery': {
      id: '/useQuery'
      path: '/useQuery'
      fullPath: '/useQuery'
      preLoaderRoute: typeof UseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useQueryClient': {
      id: '/useQueryClient'
      path: '/useQueryClient'
      fullPath: '/useQueryClient'
      preLoaderRoute: typeof UseQueryClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useQueryWIthParams': {
      id: '/useQueryWIthParams'
      path: '/useQueryWIthParams'
      fullPath: '/useQueryWIthParams'
      preLoaderRoute: typeof UseQueryWIthParamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useSuspenseQuery': {
      id: '/useSuspenseQuery'
      path: '/useSuspenseQuery'
      fullPath: '/useSuspenseQuery'
      preLoaderRoute: typeof UseSuspenseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CacheOptionsRoute: CacheOptionsRoute,
  TanStackTableRoute: TanStackTableRoute,
  TanStackTableDynamicRoute: TanStackTableDynamicRoute,
  UseInfiniteQueryRoute: UseInfiniteQueryRoute,
  UseIsFetchingRoute: UseIsFetchingRoute,
  UseMutationRoute: UseMutationRoute,
  UseQueriesAsyncRoute: UseQueriesAsyncRoute,
  UseQueriesSyncRoute: UseQueriesSyncRoute,
  UseQueryRoute: UseQueryRoute,
  UseQueryClientRoute: UseQueryClientRoute,
  UseQueryWIthParamsRoute: UseQueryWIthParamsRoute,
  UseSuspenseQueryRoute: UseSuspenseQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
